[package]
name = "eventline-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
color-eyre = "0.6.5"
crossterm = "0.29.0"
fakeit = "1.3.0"
ratatui = "0.29.0"
tokio = { version = "1.45.0", features = ["full"] }
